// Generated by scripts/gen-engine-client.ts from the engine's OpenAPI. Do not edit.
export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMcpServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saving a changed config reconnects the server on it; env and header values sent as null keep the saved ones. */
        put: operations["saveMcpServer"];
        post?: never;
        delete: operations["removeMcpServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disconnectMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMcpServerEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renames a server, saved secrets included. 409 if the new name is taken: nothing is replaced. */
        post: operations["renameMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts signing in to a remote server that requires OAuth. */
        post: operations["signInMcpServer"];
        /** Forgets a server's sign-in and reconnects it without one. */
        delete: operations["signOutMcpServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything still waiting on the user; clients read this when they hydrate. */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replyPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeProviderCredentials"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setProviderKey"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/oauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismissing a question whose answer was already saved is 409: the answer stands. */
        post: operations["rejectQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** An async question's answer is saved before this returns; resending the same answer is accepted, a different one is 409. */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Permanent removal, for archived sessions past their retention. Live turns are aborted first. */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/sessions/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abortTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expands a workspace command's template, or has an MCP server fill its prompt, and submits it as a turn. */
        post: operations["runCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/compact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summarises the older history now. Runs as the session's job: 409 while a turn runs, Stop cancels it. */
        post: operations["compactSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copies finished history into a new, independent conversation. */
        post: operations["forkSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moves a session and its subagents to another workspace. 409 while any of them is running. */
        post: operations["moveSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Moves a turn that is waiting to retry onto another model; it retries at once and the session keeps
         *     the model. 409 when nothing is waiting to retry; 400 or 401 when the model cannot be used.
         */
        post: operations["switchRetryModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undoes the conversation back to a prompt, and the files its turns and subagents changed. Files
         *     changed by someone else since are kept and listed. Again while undone moves the point.
         */
        post: operations["revertSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/spawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Spawns a thread from this conversation and starts it at once. It runs on its own from then on. */
        post: operations["spawnThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every worker the session launched, oldest first, finished ones included. */
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTodos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admits the prompt into the running turn, which switches to any model, agent or level it names from its next request, or starts a turn. */
        post: operations["submitTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/unrevert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redoes everything an undo hid, files included, keeping any changed since. */
        post: operations["unrevertSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stops one worker and nothing else: a queued one never starts, a running one stops as its turn would. */
        post: operations["abortTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaceConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace paths for an @ mention, best match first (directories end in `/`). Names only: reading a
         *     mentioned file is decided when the prompt is sent.
         */
        get: operations["findFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Aborted: {
            aborted: boolean;
        };
        Agent: {
            /** @description Front matter `background: true|false`: how a `task` for this agent runs when the call does not say. */
            background?: boolean | null;
            builtin: boolean;
            description: string;
            kind?: components["schemas"]["AgentKind"];
            model?: components["schemas"]["ModelRef"] | null;
            name: string;
            /**
             * @description A subagent's goes in its system prompt; a primary agent's rides on the prompts of the turns it
             *     runs, so switching agents mid-conversation keeps the cached prefix.
             */
            prompt?: string;
            /**
             * @description Front matter `read_only: true`: it is offered its tools as usual, but any call that would change
             *     something (a writing tool, a shell line that is not only reads, a task to a writing subagent) is refused.
             */
            readOnly?: boolean;
            /**
             * Format: int32
             * @description Front matter `steps:`: this agent's own step limit, in place of the workspace's.
             */
            steps?: number | null;
            /** @description Tool names this agent may use, any case; `!name` takes one away. Empty, or only `!` entries, means every other tool. */
            tools?: string[];
        };
        /** @enum {string} */
        AgentKind: "primary" | "subagent" | "action";
        AnswerBody: {
            /** @description One list of chosen labels per question, in order. */
            answers: string[][];
        };
        ApiKeyBody: {
            key: string;
        };
        /** @description What a call wants to do, for the permission service to judge before it runs. */
        Ask: {
            /** @description `commands` as deny rules also see them (assignments dropped, aliases spelt out), one for one. */
            canonical?: string[];
            /**
             * @description For a shell command, the simple commands it runs, each judged on its own; `None` when the line
             *     hides what it runs, so only an exact approval of the whole line allows it.
             */
            commands?: string[] | null;
            /** @description `read`, `edit`, `bash`, ...: the rule namespace. */
            kind: string;
            /** @description The thing being touched: a path, a command. Rules match it with globs. */
            pattern: string;
            title: string;
            /**
             * @description Files the shell line's redirections write. Any at all and only an exact approval of the whole
             *     line allows it: approving `git status` never approves `git status > victim.txt`.
             */
            writes?: string[];
        };
        /** @description A check is a command over files with the given extensions; `$FILE` runs it once per written file, without it once per call. */
        CheckConfig: boolean | {
            command: string[];
            extensions: string[];
        };
        /** @description One answered question: what was asked and what the user chose or typed. */
        Clarified: {
            answers: string[];
            header: string;
            question: string;
        };
        Command: {
            /** @description The prompt's arguments in order, which what follows the command fills word by word. */
            arguments?: string[];
            description: string;
            name: string;
            /** @description For an MCP server's prompt (`server:prompt`): the server that fills it; the template is unused. */
            server?: string | null;
            /** @description The prompt; see [`Command::expand`] for how what follows the command fills it. */
            template: string;
        };
        CommandBody: {
            arguments?: string;
            model?: components["schemas"]["ModelRef"] | null;
            name: string;
        };
        /** @description Everything resolved for one workspace: home config first, project config over it. */
        Config: {
            agents: components["schemas"]["Agent"][];
            checks: {
                [key: string]: components["schemas"]["CheckConfig"];
            };
            commands: components["schemas"]["Command"][];
            formatters: {
                [key: string]: components["schemas"]["FormatterConfig"];
            };
            instructions: components["schemas"]["Instruction"][];
            limits: components["schemas"]["Limits"];
            model?: components["schemas"]["ModelRef"] | null;
            permissions: components["schemas"]["Rule"][];
            /** @description Config files that could not be read; a turn refuses to start rather than run without their rules. */
            problems?: string[];
            /** @description Formatters and checks whose command the project's own drift.json sets, as `formatter:<name>` or `check:<name>`. */
            projectCommands?: string[];
            /** @description MCP servers the user vouches for, by name and what they run: their read-only tools are open to read-only agents. */
            readOnlyMcp?: {
                [key: string]: string;
            };
            skills: components["schemas"]["Skill"][];
            timeouts: {
                [key: string]: components["schemas"]["RouteTimeouts"];
            };
        };
        Control: {
            instance: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "hello";
            version: string;
        } | {
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "resync";
        } | {
            error?: components["schemas"]["ErrorBody"] | null;
            ok: boolean;
            requestId: string;
            /** @enum {string} */
            type: "question.result";
        };
        Cost: {
            /** Format: double */
            cache_read?: number;
            /** Format: double */
            cache_write?: number;
            /** Format: double */
            input?: number;
            /** Format: double */
            output?: number;
        };
        /** @enum {string} */
        Decision: "allow" | "deny" | "ask";
        EnabledBody: {
            enabled: boolean;
        };
        /**
         * @description A finished reply that did not end by itself.
         * @enum {string}
         */
        Ending: "length" | "refused";
        /** @description Engine-wide preferences the user changes in Settings. */
        EngineSettings: {
            /** @description Compact a conversation automatically when it nears its model's context window. */
            autoCompact: boolean;
            /** @description Let `task` run subagents in the background. Left out of a PUT, it stays as it is. */
            backgroundTasks?: boolean | null;
        };
        Envelope: components["schemas"]["Event"] & {
            /** Format: int64 */
            seq: number;
        };
        /**
         * @description Which generation of MCP a server speaks: 2026-07-28 and later, with no handshake and no session, or the `initialize` handshake before it.
         * @enum {string}
         */
        Era: "stateless" | "legacy";
        ErrorBody: {
            code: string;
            message: string;
        };
        Event: {
            /** @enum {string} */
            type: "workspace.created";
            workspace: components["schemas"]["Workspace"];
        } | {
            session: components["schemas"]["Session"];
            /** @enum {string} */
            type: "session.created";
        } | {
            session: components["schemas"]["Session"];
            /** @enum {string} */
            type: "session.updated";
        } | {
            sessionId: string;
            /** @enum {string} */
            type: "session.deleted";
        } | {
            sessionId: string;
            status: components["schemas"]["SessionStatus"];
            /** @enum {string} */
            type: "session.status";
        } | {
            /** Format: int32 */
            attempt: number;
            message: string;
            /** Format: int64 */
            nextAt: number;
            sessionId: string;
            /** @enum {string} */
            type: "session.retry";
        } | {
            message: components["schemas"]["Message"];
            /** @enum {string} */
            type: "message.created";
        } | {
            message: components["schemas"]["Message"];
            /** @enum {string} */
            type: "message.updated";
        } | {
            messageId: string;
            sessionId: string;
            /** @enum {string} */
            type: "message.removed";
        } | {
            part: components["schemas"]["PartRow"];
            /** @enum {string} */
            type: "part.created";
        } | {
            part: components["schemas"]["PartRow"];
            /** @enum {string} */
            type: "part.updated";
        } | {
            delta: string;
            messageId: string;
            partId: string;
            sessionId: string;
            /** @enum {string} */
            type: "part.delta";
        } | {
            sessionId: string;
            todos: components["schemas"]["Todo"][];
            /** @enum {string} */
            type: "todo.updated";
        } | {
            request: components["schemas"]["PermissionRequest"];
            /** @enum {string} */
            type: "permission.asked";
        } | {
            decision: components["schemas"]["Decision"];
            requestId: string;
            sessionId: string;
            /** @enum {string} */
            type: "permission.replied";
        } | {
            /** @enum {string} */
            type: "catalog.updated";
        } | {
            server: components["schemas"]["ServerStatus"];
            /** @enum {string} */
            type: "mcp.updated";
        } | {
            name: string;
            /** @enum {string} */
            type: "mcp.removed";
        } | {
            request: components["schemas"]["QuestionRequest"];
            /** @enum {string} */
            type: "question.asked";
        } | {
            requestId: string;
            sessionId: string;
            /** @enum {string} */
            type: "question.replied";
        } | {
            task: components["schemas"]["TaskRecord"];
            /** @enum {string} */
            type: "task.updated";
        };
        ForkBody: {
            /** @description Copy through this message; default is the last finished one, leaving out a turn in flight. */
            atMessage?: string | null;
        };
        FormatterConfig: boolean | {
            command: string[];
            extensions: string[];
        };
        /** @description Everything the server writes to the socket. */
        Frame: components["schemas"]["Control"] | components["schemas"]["Envelope"];
        Health: {
            version: string;
        };
        /** @description Replies can ride the socket so a permission prompt never waits on a new HTTP connection. */
        Incoming: (components["schemas"]["ReplyBody"] & {
            requestId: string;
        } & {
            /** @enum {string} */
            type: "permission.reply";
        }) | {
            answers?: string[][] | null;
            requestId: string;
            /** @enum {string} */
            type: "question.reply";
        };
        Instruction: {
            name: string;
            text: string;
        };
        Limit: {
            /** Format: int64 */
            context: number;
            /**
             * Format: int64
             * @description The most prompt the provider takes, when it is less than the window (gpt-5.4: 922k of 1.05M); 0 when not given.
             */
            input?: number;
            /** Format: int64 */
            output: number;
        };
        /** @description When a turn pauses for the user rather than carrying on by itself. */
        Limits: {
            /**
             * Format: int32
             * @description The same for steps whose shell commands deliberately wait, as polling does.
             */
            polls: number;
            /**
             * Format: int32
             * @description Steps in a row whose calls and results are all identical: no progress, so likely a loop.
             */
            repeats: number;
            /**
             * Format: int32
             * @description Model steps (requests) one turn may take.
             */
            steps: number;
        };
        Message: {
            /** @description The agent the session ran as when this was written. */
            agent?: string | null;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            createdAt: number;
            ending?: components["schemas"]["Ending"] | null;
            error?: string | null;
            /** Format: int64 */
            finishedAt?: number | null;
            id: string;
            model?: components["schemas"]["ModelRef"] | null;
            role: components["schemas"]["Role"];
            sessionId: string;
            status: components["schemas"]["MessageStatus"];
            /** @description A compaction summary: from here on the model sees this instead of the history before it. */
            summary?: boolean;
            usage: components["schemas"]["Usage"];
        };
        /** @enum {string} */
        MessageStatus: "streaming" | "done" | "aborted" | "error" | "paused";
        MessageWithParts: components["schemas"]["Message"] & {
            parts: components["schemas"]["PartRow"][];
        };
        /** @enum {string} */
        Mode: "foreground" | "background";
        Model: {
            attachment?: boolean;
            cost?: components["schemas"]["Cost"];
            family?: string;
            id: string;
            limit?: components["schemas"]["Limit"];
            name: string;
            /** @description Whether it reads PDFs sent whole. */
            pdf?: boolean;
            profile?: components["schemas"]["ToolProfile"];
            reasoning?: boolean;
            release_date?: string;
            temperature?: boolean;
            /** @description The reasoning levels the model offers, weakest first; empty when it has none to choose. */
            variants?: components["schemas"]["Variant"][];
        };
        ModelRef: {
            model: string;
            provider: string;
        };
        MoveBody: {
            workspaceId: string;
        };
        Moved: {
            /** @description The session and the subagents that moved with it. */
            moved: string[];
        };
        NewSessionBody: {
            /** @description `build` unless the workspace defines others; see the workspace config. */
            agent?: string | null;
            model?: components["schemas"]["ModelRef"] | null;
            title?: string;
            workspaceId: string;
        };
        NewWorkspace: {
            icon?: string;
            name: string;
            path: string;
        };
        OAuthFinishBody: {
            /** @description For `code` flows: `code#state`, the callback URL, or its query string. Empty for `auto` flows. */
            input?: string;
            /** @description The `state` from `startOAuth`; required for `auto` flows. */
            state?: string | null;
        };
        /** @description A pre-registered app as a client sends it: a `null` secret keeps the saved one for the same client id, an empty one clears it. */
        OAuthInput: {
            clientId: string;
            clientSecret?: string | null;
            scopes?: string[];
        };
        /** @enum {string} */
        OAuthMode: "max" | "console" | "chatgpt";
        OAuthStartBody: {
            mode: components["schemas"]["OAuthMode"];
        };
        OAuthStarted: {
            /** @description `code`: the user pastes what the callback page shows. `auto`: the engine catches the callback itself. */
            method: string;
            state: string;
            /** @description Open this in a browser. */
            url: string;
        };
        /** @description A pre-registered app as clients see it: whether it has a secret, never the secret. */
        OAuthView: {
            clientId: string;
            hasSecret: boolean;
            scopes: string[];
        };
        Option_: {
            description?: string;
            label: string;
        };
        Part: {
            text: string;
            /** @enum {string} */
            type: "text";
        } | {
            redacted?: string | null;
            signature?: string | null;
            text: string;
            /** @enum {string} */
            type: "reasoning";
        } | {
            callId: string;
            /** Format: int64 */
            finishedAt?: number | null;
            input: unknown;
            metadata?: unknown;
            name: string;
            output?: string | null;
            /** Format: int64 */
            startedAt?: number | null;
            status: components["schemas"]["ToolStatus"];
            title?: string | null;
            /** @enum {string} */
            type: "tool_call";
        } | {
            mime: string;
            name: string;
            /** @description For an `@` mention, the workspace file it was read from, so a client can open it; only the engine sets it. */
            path?: string | null;
            /** @enum {string} */
            type: "file";
            /** @description Data URL for now; a content-addressed blob store replaces this later. */
            url: string;
        } | {
            description: string;
            /** @description `replied`, `failed`, `stopped` or `interrupted`. */
            outcome: string;
            taskId: string;
            text: string;
            /** @enum {string} */
            type: "task_result";
            /** @description The worker's own transcript; not `session_id`, which the part row already carries. */
            workerSessionId: string;
        } | {
            items: components["schemas"]["Clarified"][];
            requestId: string;
            /** @enum {string} */
            type: "clarification";
        } | {
            auto: boolean;
            /** @description First message the model still sees verbatim after the summary; `None` keeps nothing. */
            tailFrom?: string | null;
            /** @enum {string} */
            type: "compaction";
        };
        PartRow: components["schemas"]["Part"] & {
            id: string;
            messageId: string;
            sessionId: string;
        };
        PatchSession: {
            agent?: string | null;
            archived?: boolean | null;
            model?: components["schemas"]["ModelRef"] | null;
            title?: string | null;
        };
        PermissionRequest: components["schemas"]["Ask"] & {
            callId: string;
            /** Format: int64 */
            createdAt: number;
            id: string;
            messageId: string;
            sessionId: string;
            tool: string;
        };
        Prompt: {
            /** @description The agent the session runs as from this prompt on; absent keeps the session's. Only a primary agent of the workspace. */
            agent?: string | null;
            model?: components["schemas"]["ModelRef"] | null;
            parts: components["schemas"]["Part"][];
            /** @description Client-chosen id; resubmitting with the same id returns the original receipt instead of a second turn. */
            submissionId?: string | null;
            /** @description The model's reasoning level by variant name: absent keeps the session's, null asks for the model's default. */
            variant?: string | null;
        };
        /** @description A catalog provider plus whether the engine can currently talk to it. */
        ProviderStatus: {
            connected: boolean;
            /** @description `keychain`, `env` or absent. */
            credential?: string | null;
            id: string;
            models: {
                [key: string]: components["schemas"]["Model"];
            };
            name: string;
        };
        Question: {
            /** @description Whether the user may type an answer that is not one of the options. */
            custom?: boolean;
            /** @description Short label shown as the card title. */
            header?: string;
            multiple?: boolean;
            options?: components["schemas"]["Option_"][];
            question: string;
        };
        QuestionRequest: {
            /** @description The turn went on without waiting; the answer arrives as its own prompt. */
            async?: boolean;
            callId: string;
            /** Format: int64 */
            createdAt: number;
            id: string;
            messageId: string;
            questions: components["schemas"]["Question"][];
            sessionId: string;
        };
        /** @description What one reasoning level asks of the provider: an effort its API names, or a thinking token budget. */
        Reasoning: {
            /** @enum {string} */
            kind: "effort";
            level: string;
        } | {
            /** @enum {string} */
            kind: "budget";
            /** Format: int32 */
            tokens: number;
        };
        Receipt: {
            message: components["schemas"]["Message"];
            session: components["schemas"]["Session"];
        };
        RenameBody: {
            to: string;
        };
        /** @enum {string} */
        Reply: "once" | "always" | "deny" | "stop";
        ReplyBody: {
            /** @description What the user wants the model told when refusing. */
            message?: string | null;
            pattern?: string | null;
            reply: components["schemas"]["Reply"];
        };
        RetryModelBody: {
            model: components["schemas"]["ModelRef"];
            /** @description The variant to retry at, by name: absent keeps the turn's, null asks for the model's default. */
            variant?: string | null;
        };
        /** @description An undo in progress: the user message it went back to, hidden with everything after it. */
        Revert: {
            /** @description Files the last undo or redo left alone because someone changed them after the session did. */
            kept?: string[];
            messageId: string;
        };
        RevertBody: {
            /** @description The prompt to go back to; it and everything after it are hidden. */
            messageId: string;
        };
        /** @enum {string} */
        Role: "user" | "assistant";
        /** @description A route's time limits in seconds; either may be left out to keep the route's default. */
        RouteTimeouts: {
            /**
             * Format: int64
             * @description Until the response begins.
             * @default null
             */
            headersSeconds: number | null;
            /**
             * Format: int64
             * @description Between two pieces of a streamed reply.
             * @default null
             */
            idleSeconds: number | null;
        };
        Rule: {
            decision: components["schemas"]["Decision"];
            kind: string;
            pattern: string;
        };
        /** @description A config as a client sends it. A `null` value keeps the one saved under that name, so a secret can be kept without being read. */
        ServerConfigInput: {
            args?: string[];
            command: string;
            cwd?: string | null;
            env?: {
                [key: string]: string | null;
            };
            /** Format: int64 */
            timeoutSeconds?: number | null;
            /** @enum {string} */
            type: "stdio";
        } | {
            headers?: {
                [key: string]: string | null;
            };
            oauth?: components["schemas"]["OAuthInput"] | null;
            /** Format: int64 */
            timeoutSeconds?: number | null;
            /** @enum {string} */
            type: "http";
            url: string;
        } | {
            headers?: {
                [key: string]: string | null;
            };
            oauth?: components["schemas"]["OAuthInput"] | null;
            /** Format: int64 */
            timeoutSeconds?: number | null;
            /** @enum {string} */
            type: "sse";
            url: string;
        };
        ServerConfigView: {
            args: string[];
            command: string;
            cwd?: string | null;
            /** @description Names only. */
            env: string[];
            /** Format: int64 */
            timeoutSeconds?: number | null;
            /** @enum {string} */
            type: "stdio";
        } | {
            /** @description Names only. */
            headers: string[];
            oauth?: components["schemas"]["OAuthView"] | null;
            /** Format: int64 */
            timeoutSeconds?: number | null;
            /** @enum {string} */
            type: "http";
            url: string;
        } | {
            /** @description Names only. */
            headers: string[];
            oauth?: components["schemas"]["OAuthView"] | null;
            /** Format: int64 */
            timeoutSeconds?: number | null;
            /** @enum {string} */
            type: "sse";
            url: string;
        };
        ServerStatus: components["schemas"]["ServerView"] & {
            era?: components["schemas"]["Era"] | null;
            error?: string | null;
            /** @description The server refused to connect until the user signs in (`POST /mcp/{name}/signin`). */
            needsSignIn: boolean;
            /** @description The MCP protocol version the server agreed to; absent until connected. */
            protocol?: string | null;
            /** @description A sign-in is kept for it (`DELETE /mcp/{name}/signin` forgets it). */
            signedIn: boolean;
            state: components["schemas"]["State"];
            tools: components["schemas"]["ToolInfo"][];
            /** @description How the engine talks to it. */
            transport: components["schemas"]["Transport"];
        };
        /** @description A server as clients see it: every field but the values of its env vars and headers. */
        ServerView: {
            config: components["schemas"]["ServerConfigView"];
            enabled: boolean;
            name: string;
            /** Format: int64 */
            updatedAt: number;
        };
        Session: {
            agent: string;
            /** Format: int64 */
            archivedAt?: number | null;
            /** @description For a spawned thread, the last source message copied into it. */
            branchCutoff?: string | null;
            /** Format: int64 */
            createdAt: number;
            id: string;
            model?: components["schemas"]["ModelRef"] | null;
            parentId?: string | null;
            revert?: components["schemas"]["Revert"] | null;
            /** @description Whether a turn is in flight right now; set by the API, never stored. */
            running?: boolean;
            title: string;
            /** Format: int64 */
            updatedAt: number;
            /** @description The reasoning variant the user last chose; turns the engine starts itself run with it too. */
            variant?: string | null;
            visibility: components["schemas"]["Visibility"];
            workspaceId: string;
        };
        /** @enum {string} */
        SessionStatus: "idle" | "running";
        SignInPage: {
            /** @description Open this in the browser; when the browser comes back, the server connects signed in. */
            url: string;
        };
        Skill: {
            description: string;
            name: string;
            /** @description Directory holding SKILL.md and whatever it references. */
            path: string;
        };
        SpawnBody: {
            /** @description What the new thread should do; it starts with a copy of this conversation and works out what it needs. */
            instruction: string;
        };
        /** @enum {string} */
        State: "disabled" | "disconnected" | "connecting" | "connected" | "failed";
        /** @description One worker: who launched it, how it runs and why, how it ended, and whether its parent has it. */
        TaskRecord: {
            agent: string;
            /** @description The `task` call that launched it. */
            callId: string;
            /** Format: int64 */
            createdAt: number;
            /** @description The result reached the parent (as the call's own result, or delivered later). */
            delivered: boolean;
            /** @description Why this owed result has not been handed over yet; it is retried when that may have changed. */
            deliveryError?: string | null;
            description: string;
            /** Format: int64 */
            finishedAt?: number | null;
            /** @description Kept from waking a stopped parent; it goes along with the parent's next prompt instead. */
            held: boolean;
            id: string;
            mode: components["schemas"]["Mode"];
            parentSessionId: string;
            /** @description Why this mode: `requested`, `agent default`, `default` or `background turned off`. */
            reason: string;
            result?: string | null;
            /** @description The worker's own transcript. */
            sessionId: string;
            state: components["schemas"]["TaskState"];
        };
        /** @enum {string} */
        TaskState: "queued" | "running" | "replied" | "failed" | "stopped" | "interrupted";
        Todo: {
            content: string;
            priority?: string;
            status: components["schemas"]["TodoStatus"];
        };
        /** @enum {string} */
        TodoStatus: "pending" | "in_progress" | "completed" | "cancelled";
        ToolInfo: {
            description: string;
            name: string;
            read_only: boolean;
        };
        /**
         * @description How a model edits files: what its training makes it good at, decided here and nowhere else.
         * @enum {string}
         */
        ToolProfile: "edit" | "apply_patch";
        /** @enum {string} */
        ToolStatus: "pending" | "running" | "done" | "error" | "denied";
        /**
         * @description The wire a server is spoken to over; a stateless transport will join these.
         * @enum {string}
         */
        Transport: "stdio" | "streamable_http" | "sse";
        /** @description The session after an undo or redo, and the files it left alone. */
        Undone: {
            /** @description Changed by someone else since the session last wrote them. */
            kept: string[];
            session: components["schemas"]["Session"];
            /** @description Seen changing while a command ran, which does not show who changed them. */
            unattributed: string[];
        };
        Usage: {
            /** Format: int64 */
            cacheRead: number;
            /** Format: int64 */
            cacheWrite: number;
            /** Format: int64 */
            input: number;
            /** Format: int64 */
            output: number;
        };
        Variant: components["schemas"]["Reasoning"] & {
            name: string;
        };
        /** @enum {string} */
        Visibility: "hidden" | "sibling";
        Workspace: {
            icon: string;
            id: string;
            /** Format: int64 */
            lastUsed: number;
            name: string;
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    events: {
        parameters: {
            query?: {
                /** @description Last `seq` the client has applied; omit on first connect. */
                cursor?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket; every message is a Frame */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listMcpServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"][];
                };
            };
        };
    };
    saveMcpServer: {
        parameters: {
            query?: {
                /** @description Adding a server: refused with 409 if one has the name, rather than replacing it. */
                create?: boolean;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerConfigInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    connectMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disconnectMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMcpServerEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renameMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signInMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInPage"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signOutMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRequest"][];
                };
            };
        };
    };
    replyPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
        };
    };
    removeProviderCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setProviderKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStarted"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finishOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthFinishBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionRequest"][];
                };
            };
        };
    };
    rejectQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description Archived sessions instead of live ones. */
                archived?: boolean;
                /** @description Page: sessions updated before this session id. */
                before?: string | null;
                limit?: number | null;
                /** @description Restrict to one workspace; omit for every workspace. */
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSessionBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: {
                /** @description Only while the session is still archived: the archive purge, which a restore must always win against. 409 if it is not. */
                archived?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abortTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aborted"];
                };
            };
        };
    };
    runCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandBody"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compactSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forkSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Page: messages before this message id. */
                before?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageWithParts"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moveSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Moved"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    switchRetryModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryModelBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revertSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevertBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Undone"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    spawnThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpawnBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRecord"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Prompt"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unrevertSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Undone"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettings"];
                };
            };
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettings"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRecord"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abortTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRecord"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkspace"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaceConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findFiles: {
        parameters: {
            query?: {
                /** @description At most this many paths; default 20. */
                limit?: number | null;
                /** @description What the user typed after `@`. */
                query?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
