// Generated by scripts/gen-engine-client.ts from the engine's OpenAPI. Do not edit.
export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMcpServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saving a changed config disconnects the server and withdraws approval until the user approves it again. */
        put: operations["saveMcpServer"];
        post?: never;
        delete: operations["removeMcpServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approves the config exactly as stored now, then connects. */
        post: operations["approveMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disconnectMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{name}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMcpServerEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything still waiting on the user; clients read this when they hydrate. */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replyPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeProviderCredentials"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setProviderKey"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/oauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Permanent removal, for archived sessions past their retention. Live turns are aborted first. */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/sessions/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abortTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a reviewed branch and starts it. The new conversation is independent of its source. */
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/branch/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drafts the handoff for a branch. Makes one model request; stores nothing. */
        post: operations["draftBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expands a workspace command's template and submits it as a turn. */
        post: operations["runCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/compact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summarises the older history now. Runs as the session's job: 409 while a turn runs, Stop cancels it. */
        post: operations["compactSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copies finished history into a new, independent conversation. */
        post: operations["forkSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moves a session and its subagents to another workspace. 409 while any of them is running. */
        post: operations["moveSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Moves a turn that is waiting to retry onto another model; it retries at once and the session keeps
         *     the model. 409 when nothing is waiting to retry; 400 or 401 when the model cannot be used.
         */
        post: operations["switchRetryModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undoes the conversation back to a prompt, and the files its turns and subagents changed. Files
         *     changed by someone else since are kept and listed. Again while undone moves the point.
         */
        post: operations["revertSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTodos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/unrevert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redoes everything an undo hid, files included, keeping any changed since. */
        post: operations["unrevertSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaceConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Aborted: {
            aborted: boolean;
        };
        Agent: {
            builtin: boolean;
            description: string;
            kind?: components["schemas"]["AgentKind"];
            model?: components["schemas"]["ModelRef"] | null;
            name: string;
            /** @description Appended to the system prompt when this agent runs. */
            prompt?: string;
            /** @description Tool names this agent may use; empty means every tool. */
            tools?: string[];
        };
        /** @enum {string} */
        AgentKind: "primary" | "subagent" | "action";
        AnswerBody: {
            /** @description One list of chosen labels per question, in order. */
            answers: string[][];
        };
        ApiKeyBody: {
            key: string;
        };
        /** @description What a call wants to do, for the permission service to judge before it runs. */
        Ask: {
            /** @description `read`, `edit`, `bash`, ...: the rule namespace. */
            kind: string;
            /** @description The thing being touched: a path, a command. Rules match it with globs. */
            pattern: string;
            title: string;
        };
        /** @description What the user reviews before a branch exists. Nothing is stored until they confirm. */
        BranchDraft: {
            /** @description The last source message the summary covers; absent for a conversation with no finished replies. */
            cutoff?: string | null;
            excerpts: string;
            goal: string;
            summary: string;
            title: string;
        };
        BranchGoal: {
            goal: string;
        };
        Command: {
            description: string;
            name: string;
            /** @description The prompt; `$ARGUMENTS` is replaced with what follows the command. */
            template: string;
        };
        CommandBody: {
            arguments?: string;
            model?: components["schemas"]["ModelRef"] | null;
            name: string;
        };
        /** @description Everything resolved for one workspace: home config first, project config over it. */
        Config: {
            agents: components["schemas"]["Agent"][];
            commands: components["schemas"]["Command"][];
            formatters: {
                [key: string]: components["schemas"]["FormatterConfig"];
            };
            instructions: components["schemas"]["Instruction"][];
            model?: components["schemas"]["ModelRef"] | null;
            permissions: components["schemas"]["Rule"][];
            skills: components["schemas"]["Skill"][];
        };
        Control: {
            instance: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "hello";
            version: string;
        } | {
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "resync";
        };
        Cost: {
            /** Format: double */
            cache_read?: number;
            /** Format: double */
            cache_write?: number;
            /** Format: double */
            input?: number;
            /** Format: double */
            output?: number;
        };
        /** @enum {string} */
        Decision: "allow" | "deny" | "ask";
        EnabledBody: {
            enabled: boolean;
        };
        /** @description Engine-wide preferences the user changes in Settings. */
        EngineSettings: {
            /** @description Compact a conversation automatically when it nears its model's context window. */
            autoCompact: boolean;
        };
        Envelope: components["schemas"]["Event"] & {
            /** Format: int64 */
            seq: number;
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        Event: {
            /** @enum {string} */
            type: "workspace.created";
            workspace: components["schemas"]["Workspace"];
        } | {
            session: components["schemas"]["Session"];
            /** @enum {string} */
            type: "session.created";
        } | {
            session: components["schemas"]["Session"];
            /** @enum {string} */
            type: "session.updated";
        } | {
            sessionId: string;
            /** @enum {string} */
            type: "session.deleted";
        } | {
            sessionId: string;
            status: components["schemas"]["SessionStatus"];
            /** @enum {string} */
            type: "session.status";
        } | {
            /** Format: int32 */
            attempt: number;
            message: string;
            /** Format: int64 */
            nextAt: number;
            sessionId: string;
            /** @enum {string} */
            type: "session.retry";
        } | {
            message: components["schemas"]["Message"];
            /** @enum {string} */
            type: "message.created";
        } | {
            message: components["schemas"]["Message"];
            /** @enum {string} */
            type: "message.updated";
        } | {
            messageId: string;
            sessionId: string;
            /** @enum {string} */
            type: "message.removed";
        } | {
            part: components["schemas"]["PartRow"];
            /** @enum {string} */
            type: "part.created";
        } | {
            part: components["schemas"]["PartRow"];
            /** @enum {string} */
            type: "part.updated";
        } | {
            delta: string;
            messageId: string;
            partId: string;
            sessionId: string;
            /** @enum {string} */
            type: "part.delta";
        } | {
            sessionId: string;
            todos: components["schemas"]["Todo"][];
            /** @enum {string} */
            type: "todo.updated";
        } | {
            request: components["schemas"]["PermissionRequest"];
            /** @enum {string} */
            type: "permission.asked";
        } | {
            decision: components["schemas"]["Decision"];
            requestId: string;
            sessionId: string;
            /** @enum {string} */
            type: "permission.replied";
        } | {
            /** @enum {string} */
            type: "catalog.updated";
        } | {
            server: components["schemas"]["ServerStatus"];
            /** @enum {string} */
            type: "mcp.updated";
        } | {
            name: string;
            /** @enum {string} */
            type: "mcp.removed";
        } | {
            request: components["schemas"]["QuestionRequest"];
            /** @enum {string} */
            type: "question.asked";
        } | {
            requestId: string;
            sessionId: string;
            /** @enum {string} */
            type: "question.replied";
        };
        ForkBody: {
            /** @description Copy through this message; default is the last finished one, leaving out a turn in flight. */
            atMessage?: string | null;
        };
        FormatterConfig: boolean | {
            command: string[];
            extensions: string[];
        };
        /** @description Everything the server writes to the socket. */
        Frame: components["schemas"]["Control"] | components["schemas"]["Envelope"];
        Health: {
            version: string;
        };
        /** @description Replies can ride the socket so a permission prompt never waits on a new HTTP connection. */
        Incoming: (components["schemas"]["ReplyBody"] & {
            requestId: string;
        } & {
            /** @enum {string} */
            type: "permission.reply";
        }) | {
            answers?: string[][] | null;
            requestId: string;
            /** @enum {string} */
            type: "question.reply";
        };
        Instruction: {
            name: string;
            text: string;
        };
        Limit: {
            /** Format: int64 */
            context: number;
            /** Format: int64 */
            output: number;
        };
        Message: {
            /** Format: double */
            cost: number;
            /** Format: int64 */
            createdAt: number;
            error?: string | null;
            /** Format: int64 */
            finishedAt?: number | null;
            id: string;
            model?: components["schemas"]["ModelRef"] | null;
            role: components["schemas"]["Role"];
            sessionId: string;
            status: components["schemas"]["MessageStatus"];
            /** @description A compaction summary: from here on the model sees this instead of the history before it. */
            summary?: boolean;
            usage: components["schemas"]["Usage"];
        };
        /** @enum {string} */
        MessageStatus: "streaming" | "done" | "aborted" | "error";
        MessageWithParts: components["schemas"]["Message"] & {
            parts: components["schemas"]["PartRow"][];
        };
        Model: {
            attachment?: boolean;
            cost?: components["schemas"]["Cost"];
            family?: string;
            id: string;
            limit?: components["schemas"]["Limit"];
            name: string;
            profile?: components["schemas"]["ToolProfile"];
            reasoning?: boolean;
            release_date?: string;
            temperature?: boolean;
        };
        ModelRef: {
            model: string;
            provider: string;
        };
        MoveBody: {
            workspaceId: string;
        };
        Moved: {
            /** @description The session and the subagents that moved with it. */
            moved: string[];
        };
        NewSessionBody: {
            /** @description `build` unless the workspace defines others; see the workspace config. */
            agent?: string | null;
            model?: components["schemas"]["ModelRef"] | null;
            title?: string;
            workspaceId: string;
        };
        NewWorkspace: {
            icon?: string;
            name: string;
            path: string;
        };
        OAuthFinishBody: {
            /** @description For `code` flows: `code#state`, the callback URL, or its query string. Empty for `auto` flows. */
            input?: string;
            /** @description The `state` from `startOAuth`; required for `auto` flows. */
            state?: string | null;
        };
        /** @enum {string} */
        OAuthMode: "max" | "console" | "chatgpt";
        OAuthStartBody: {
            mode: components["schemas"]["OAuthMode"];
        };
        OAuthStarted: {
            /** @description `code`: the user pastes what the callback page shows. `auto`: the engine catches the callback itself. */
            method: string;
            state: string;
            /** @description Open this in a browser. */
            url: string;
        };
        Option_: {
            description?: string;
            label: string;
        };
        Part: {
            text: string;
            /** @enum {string} */
            type: "text";
        } | {
            redacted?: string | null;
            signature?: string | null;
            text: string;
            /** @enum {string} */
            type: "reasoning";
        } | {
            callId: string;
            /** Format: int64 */
            finishedAt?: number | null;
            input: unknown;
            metadata?: unknown;
            name: string;
            output?: string | null;
            /** Format: int64 */
            startedAt?: number | null;
            status: components["schemas"]["ToolStatus"];
            title?: string | null;
            /** @enum {string} */
            type: "tool_call";
        } | {
            mime: string;
            name: string;
            /** @enum {string} */
            type: "file";
            /** @description Data URL for now; a content-addressed blob store replaces this later. */
            url: string;
        } | {
            auto: boolean;
            /** @description First message the model still sees verbatim after the summary; `None` keeps nothing. */
            tailFrom?: string | null;
            /** @enum {string} */
            type: "compaction";
        };
        PartRow: components["schemas"]["Part"] & {
            id: string;
            messageId: string;
            sessionId: string;
        };
        PatchSession: {
            agent?: string | null;
            archived?: boolean | null;
            model?: components["schemas"]["ModelRef"] | null;
            title?: string | null;
        };
        PermissionRequest: components["schemas"]["Ask"] & {
            callId: string;
            /** Format: int64 */
            createdAt: number;
            id: string;
            messageId: string;
            sessionId: string;
            tool: string;
        };
        Prompt: {
            model?: components["schemas"]["ModelRef"] | null;
            parts: components["schemas"]["Part"][];
            /** @description Client-chosen id; resubmitting with the same id returns the original receipt instead of a second turn. */
            submissionId?: string | null;
            /** Format: int32 */
            thinkingBudget?: number | null;
        };
        /** @description A catalog provider plus whether the engine can currently talk to it. */
        ProviderStatus: {
            connected: boolean;
            /** @description `keychain`, `env` or absent. */
            credential?: string | null;
            id: string;
            models: {
                [key: string]: components["schemas"]["Model"];
            };
            name: string;
        };
        Question: {
            /** @description Whether the user may type an answer that is not one of the options. */
            custom?: boolean;
            /** @description Short label shown as the card title. */
            header?: string;
            multiple?: boolean;
            options?: components["schemas"]["Option_"][];
            question: string;
        };
        QuestionRequest: {
            callId: string;
            /** Format: int64 */
            createdAt: number;
            id: string;
            messageId: string;
            questions: components["schemas"]["Question"][];
            sessionId: string;
        };
        Receipt: {
            message: components["schemas"]["Message"];
            session: components["schemas"]["Session"];
        };
        /** @enum {string} */
        Reply: "once" | "always" | "deny";
        ReplyBody: {
            pattern?: string | null;
            reply: components["schemas"]["Reply"];
        };
        RetryModelBody: {
            model: components["schemas"]["ModelRef"];
        };
        /** @description An undo in progress: the user message it went back to, hidden with everything after it. */
        Revert: {
            /** @description Files the last undo or redo left alone because someone changed them after the session did. */
            kept?: string[];
            messageId: string;
        };
        RevertBody: {
            /** @description The prompt to go back to; it and everything after it are hidden. */
            messageId: string;
        };
        /** @enum {string} */
        Role: "user" | "assistant";
        Rule: {
            decision: components["schemas"]["Decision"];
            kind: string;
            pattern: string;
        };
        ServerConfig: {
            args?: string[];
            command: string;
            env?: {
                [key: string]: string;
            };
            /** @enum {string} */
            type: "stdio";
        } | {
            headers?: {
                [key: string]: string;
            };
            /** @enum {string} */
            type: "http";
            url: string;
        };
        ServerRow: {
            approvedHash?: string | null;
            config: components["schemas"]["ServerConfig"];
            enabled: boolean;
            name: string;
            /** Format: int64 */
            updatedAt: number;
        };
        ServerStatus: components["schemas"]["ServerRow"] & {
            error?: string | null;
            state: components["schemas"]["State"];
            tools: components["schemas"]["ToolInfo"][];
        };
        Session: {
            agent: string;
            /** Format: int64 */
            archivedAt?: number | null;
            /** @description For a branched conversation, the last source message its handoff summarised. */
            branchCutoff?: string | null;
            /** Format: int64 */
            createdAt: number;
            id: string;
            model?: components["schemas"]["ModelRef"] | null;
            parentId?: string | null;
            revert?: components["schemas"]["Revert"] | null;
            /** @description Whether a turn is in flight right now; set by the API, never stored. */
            running?: boolean;
            title: string;
            /** Format: int64 */
            updatedAt: number;
            visibility: components["schemas"]["Visibility"];
            workspaceId: string;
        };
        /** @enum {string} */
        SessionStatus: "idle" | "running";
        Skill: {
            description: string;
            name: string;
            /** @description Directory holding SKILL.md and whatever it references. */
            path: string;
        };
        /** @enum {string} */
        State: "disabled" | "needs_approval" | "disconnected" | "connecting" | "connected" | "failed";
        Todo: {
            content: string;
            priority?: string;
            status: components["schemas"]["TodoStatus"];
        };
        /** @enum {string} */
        TodoStatus: "pending" | "in_progress" | "completed" | "cancelled";
        ToolInfo: {
            description: string;
            name: string;
            read_only: boolean;
        };
        /**
         * @description How a model edits files: what its training makes it good at, decided here and nowhere else.
         * @enum {string}
         */
        ToolProfile: "edit" | "apply_patch";
        /** @enum {string} */
        ToolStatus: "pending" | "running" | "done" | "error" | "denied";
        /** @description The session after an undo or redo, and the files left alone because they changed since. */
        Undone: {
            kept: string[];
            session: components["schemas"]["Session"];
        };
        Usage: {
            /** Format: int64 */
            cacheRead: number;
            /** Format: int64 */
            cacheWrite: number;
            /** Format: int64 */
            input: number;
            /** Format: int64 */
            output: number;
        };
        /** @enum {string} */
        Visibility: "hidden" | "sibling";
        Workspace: {
            icon: string;
            id: string;
            /** Format: int64 */
            lastUsed: number;
            name: string;
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    events: {
        parameters: {
            query?: {
                /** @description Last `seq` the client has applied; omit on first connect. */
                cursor?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket; every message is a Frame */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listMcpServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"][];
                };
            };
        };
    };
    saveMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerConfig"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
        };
    };
    removeMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    connectMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disconnectMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMcpServerEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRequest"][];
                };
            };
        };
    };
    replyPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
        };
    };
    removeProviderCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setProviderKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStarted"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finishOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthFinishBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionRequest"][];
                };
            };
        };
    };
    rejectQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description Archived sessions instead of live ones. */
                archived?: boolean;
                /** @description Page: sessions updated before this session id. */
                before?: string | null;
                limit?: number | null;
                /** @description Restrict to one workspace; omit for every workspace. */
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSessionBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abortTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aborted"];
                };
            };
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchDraft"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    draftBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDraft"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandBody"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compactSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forkSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Page: messages before this message id. */
                before?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageWithParts"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moveSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Moved"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    switchRetryModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryModelBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revertSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevertBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Undone"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Prompt"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unrevertSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Undone"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettings"];
                };
            };
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettings"];
                };
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkspace"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaceConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
