// Regenerates src/engine/native/types.ts from the engine's OpenAPI. Run after changing any route; `--check` only reports a stale file.
import openapiTS, { astToString } from "openapi-typescript";
import { resolve } from "node:path";
import { $ } from "bun";

const root = resolve(import.meta.dir, "..");
export const output = resolve(root, "src/engine/native/types.ts");

export async function generate() {
    const spec = await $`cargo run -q -p drift-engined -- --openapi`.cwd(root).text();
    const ast = await openapiTS(JSON.parse(spec), { alphabetize: true });
    return `// Generated by scripts/gen-engine-client.ts from the engine's OpenAPI. Do not edit.\n${astToString(ast)}`;
}

if (import.meta.main) {
    const generated = await generate();
    if (process.argv.includes("--check")) {
        if ((await Bun.file(output).text()) !== generated) {
            console.error(`${output} is stale: run bun scripts/gen-engine-client.ts`);
            process.exit(1);
        }
    } else {
        await Bun.write(output, generated);
        console.log(`wrote ${output}`);
    }
}
