// Regenerates src/engine/native/types.ts from the engine's OpenAPI. Run after changing any route.
import openapiTS, { astToString } from "openapi-typescript"
import { $ } from "bun"
import { resolve } from "node:path"

const root = resolve(import.meta.dir, "..")
export const output = resolve(root, "src/engine/native/types.ts")

export async function generate() {
  const spec = await $`cargo run -q -p drift-engined -- --openapi`.cwd(root).text()
  const ast = await openapiTS(JSON.parse(spec), { alphabetize: true })
  return `// Generated by scripts/gen-engine-client.ts from the engine's OpenAPI. Do not edit.\n${astToString(ast)}`
}

if (import.meta.main) {
  await Bun.write(output, await generate())
  console.log(`wrote ${output}`)
}
